### ISSUE TITLE
ailed to initialize the frame cache caused by access failure to the TCAS file.

### ISSUE THREAD

**Issue by unixfx** [emako/tcasFilter-vapoursynth#1]
Hi good day
I have tested the filter and got an error
src = core.tcax.TcasSub(src, file=u'munto_ed.tcas')
File "src\cython\vapoursynth.pyx", line 2580, in vapoursynth.Function.__call__
vapoursynth.Error: TcasFilter: failed to initialize the frame cache caused by access failure to the TCAS file.

![image](https://github.com/emako/tcasFilter-vapoursynth/assets/10103810/222b8681-3733-4ec3-8c56-d729218d3807)

**Comment by emako** [comment]
Can you use the example? and please tell me your vapoursynth version.

```python
import vapoursynth as vs

core = vs.core
src = core.lsmas.LibavSMASHSource(u'example.mp4')
src = core.tcax.TcasSub(src, file=u'example.tcas')
src.set_output()
```
![image](https://github.com/emako/tcasFilter-vapoursynth/assets/24737061/a3b3f4e2-5d98-4d5f-b9e1-1918561bdeb3)

**Comment by unixfx** [comment]
It works now, it seems I did something wrong >_<
Thanx =)
